# ================================================================
# SpendWise - Production Environment Properties
# ================================================================

# Prod Database
spring.datasource.url=jdbc:mysql://localhost:3306/spendwise_db?useSSL=true&serverTimezone=Asia/Dhaka&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# No SQL in prod
spring.jpa.show-sql=false

# Cache on in prod
spring.thymeleaf.cache=true

# Info level in prod
logging.level.root=WARN
logging.level.com.spendwise=INFO
